### ISSUE TITLE
Conversion failed when converting the varchar value '$$LINK$$;' to data type int.

### ISSUE THREAD

**Issue by SIT-kenger** [kenger-dk/DAW#13]
Column description "link" is not working.

getting this error when testing
Conversion failed when converting the varchar value '$$LINK$$;' to data type int.

**Comment by SIT-kenger** [comment]
ah.. cannot put a link on a [int] column.
but the link is not correct resolved, the {0} is just replaced with the LinkValues, not resolved as the column value

**Comment by kenger-dk** [comment]
fixed in 2.3.5, missed a typecast of column
