### ISSUE TITLE
Input string was not in a correct format.

### ISSUE THREAD

**Issue by SIT-kenger** [kenger-dk/DAW#17]
when making a equal on a empty int..
could this be fixed? or should I change the type to a nvarchar?
fail:
list.aspx?table=35&r=1&p=27&k=VlanId&t=7&q=

**Comment by kenger-dk** [comment]
it should be changed to a type that supports '' as a search criteria.
or wait until DAW supportes OR keywords in filters.. not scheduled or requested yet.
