### ISSUE TITLE
maybe issue with link generation of null values..

### ISSUE THREAD

**Issue by SIT-kenger** [kenger-dk/DAW#20]
i think we have a issue when a link is generated with a value of Null...

/List.aspx?table=75&k=TrunkRange&t=3&q={0}&k=VlanType&t=3&q={1}&k=VlanID&t=3&q={2}&k=Cluster&t=4&q=ADM

TrunkRange,VlanType,VlanID

**Comment by kenger-dk** [comment]
fixed,
if key value is null, it's replaced by a '' instead, thats makes links visible after all, just with a empty argument output..

**Comment by kenger-dk** [comment]
make test in test, and request patch for 2.3 if needed

**Comment by SIT-kenger** [comment]
working in test, patch for 2.3, please
