### ISSUE TITLE
2.4, Column 'LastTriggered' does not belong to table .

### ISSUE THREAD

**Issue by SIT-kenger** [kenger-dk/DAW#25]
error after adding custom data webhook to table...?
Line 159:                        <% foreach ( var o in GetCustomWebHooks ) {%>
Line 160:                        "setthook<%=o.id%>": { name: "<%=o.Name%>", value: "<%=o.Name%>", typ: "CustomWebHook" },
Line 161:                        <%}%>

**Comment by SIT-kenger** [comment]
LastTriggered column is missing in CustomWebHooks

**Comment by kenger-dk** [comment]
sql.txt updated
