### ISSUE TITLE
Allow html inputs on some fields?

### ISSUE THREAD

**Issue by SIT-kenger** [kenger-dk/DAW#28]
can we make some kind of function.. maybe a ColumnDescription, that will allow HTML input in Create og Edit data?

**Comment by SIT-kenger** [comment]
maybe like this: https://stackoverflow.com/questions/4146309/in-a-text-box-in-asp-net-how-to-allow-it

**Comment by kenger-dk** [comment]
ready for testing

**Comment by SIT-kenger** [comment]
works, but line breaks is removed.. maybe because the hidden input is not multilined?

**Comment by kenger-dk** [comment]
correct, fixed :), case closed
