### ISSUE TITLE
Screen height, autorow calculation

### ISSUE THREAD

**Issue by SIT-kenger** [kenger-dk/DAW#3]
row number of records on test screen.
maybo also a button to force re-calculate row number

**Comment by SIT-kenger** [comment]
calc rows was 28, should have been 24 with allot of filters

**Comment by kenger-dk** [comment]
new method implemented,  going to test. (Hit the DynHeight button)

**Comment by kenger-dk** [comment]
have been fixed, it will not do it automatic, only when "juster højde" is pressed.
the number of rows is saved to cookie afterwards
