### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by SIT-kenger** [kenger-dk/DAW#5]
System.InvalidOperationException: Sequence contains no matching element
DAWGrid.ascx.cs:59

Rapport - Samlet patchvurderinger
unknown SQL

**Comment by SIT-kenger** [comment]
SELECT [Produkt], [Nuværende patch versions niveau], [LatestPatchLevel], [Omfang], [Sorting] FROM ( SELECT [dbo].[v_RapportCombinedPatchLevel].[Produkt] as [Produkt], [dbo].[v_RapportCombinedPatchLevel].[Nuværende patch versions niveau] as [Nuværende patch versions niveau], [dbo].[v_RapportCombinedPatchLevel].[LatestPatchLevel] as [LatestPatchLevel], [dbo].[v_RapportCombinedPatchLevel].[Omfang] as [Omfang], [dbo].[v_RapportCombinedPatchLevel].[Sorting] as [Sorting], ROW_NUMBER() OVER( ORDER BY v_RapportCombinedPatchLevel.Produkt ) AS RowRank FROM dbo.v_RapportCombinedPatchLevel ) AS DynamicTable WHERE RowRank BETWEEN 1 AND 21

**Comment by kenger-dk** [comment]
caused by columns with non standard letters, in this case æ, fixet.
