### ISSUE TITLE
data viewer json objects

### ISSUE THREAD

**Issue by SIT-kenger** [kenger-dk/DAW#51]
make it possible to view json objects like: https://www.npmjs.com/package/jquery.json-viewer
maybe just in view mode, but why not click on it in list mode? js popup with json viewer?
enable with column descriptions

**Comment by SIT-kenger** [comment]
also xml viewer could be nice

**Comment by kenger-dk** [comment]
see file:///C:/temp/test/jsonview.html

**Comment by kenger-dk** [comment]
Fixed, controlled by column descriptions
