### ISSUE TITLE
Save change to favorites

### ISSUE THREAD

**Issue by Mihgo** [kenger-dk/DAW#54]
When i have point out, witch colums i want to see and set/save it for the favorites - could it be nice if the change could be saved. 
So i can make miniviews in the favorites.

**Comment by kenger-dk** [comment]
fixed, and ready for test.
no patch for 2.4 will be created, unless really needed.

**Comment by kenger-dk** [comment]
if there are to many issues with fav. we are considering a re-write, please keep reporting
