### ISSUE TITLE
After setting favorites SN data show what choosing

### ISSUE THREAD

**Issue by Mihgo** [kenger-dk/DAW#57]
If you click on that favorites you have make (from SN BusinessService), and would like to make a new on the same (SNBusinessService). The SNBusinessService is stock on the favorites i'd make. 

Workarround is to click on one of the other SN data(ex. SNkunder), and then back to (ex. SNBusinessService) to get all colums, an make a new one.

**Comment by SIT-kenger** [comment]
as it sounds, you want the table to reset when you click on the same table in the menu, corrent?

**Comment by kenger-dk** [comment]
a click on menu item, that is already selected, will now raise a page reload / datagrid reset.
