### ISSUE TITLE
Active user monitor

### ISSUE THREAD

**Issue by SIT-kenger** [kenger-dk/DAW#59]
could need a admin page that shows the number of active users.
ex. in case of maintenance

**Comment by kenger-dk** [comment]
ready for testing

**Comment by SIT-kenger** [comment]
missing setting rule for the table (deployment)

**Comment by SIT-kenger** [comment]
01 - UserActivity.txt contains a db name..

**Comment by SIT-kenger** [comment]
[HttpException (0x80004005): Session state is not available in this context.]
   System.Web.HttpApplication.get_Session() +4758144
   kenger.DAW.WebUI.Global.Application_AcquireRequestState(Object sender, EventArgs e) in \Global.asax.cs:25
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +139
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +195
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +88

**Comment by kenger-dk** [comment]
patched.. ready for testing.. again
