### ISSUE TITLE
table issue with nigtly build

### ISSUE THREAD

**Issue by SIT-kenger** [kenger-dk/DAW#62]
getting error when try to open table..

Table argument was incorrect, not id, not guid ''
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Exception: Table argument was incorrect, not id, not guid ''

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[Exception: Table argument was incorrect, not id, not guid '']

[Exception: Table was not found]
   kenger.DAW.WebUI.Helpers.Web.get_TableID() in C:\Code\SVN\kenger\Projects\kenger.DAW\trunk\DAW.WebUI\Helpers\Web.cs:40
   kenger.DAW.WebUI.Menu.Page_Load(Object sender, EventArgs e) in C:\Code\SVN\kenger\Projects\kenger.DAW\trunk\DAW.WebUI\Menu.ascx.cs:15
   System.Web.UI.Control.OnLoad(EventArgs e) +106
   System.Web.UI.Control.LoadRecursive() +68
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Control.LoadRecursive() +162
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3785

**Comment by kenger-dk** [comment]
bug found, and fixed
