### ISSUE TITLE
Højreklikke filtre navn med æøå

### ISSUE THREAD

**Issue by Mihgo** [kenger-dk/DAW#68]
Hvis jeg højreklikker på et navn jeg gerne vil lave en filtrering på, kan den ikke filtrere på navnet, da den ikke kan omsætte æøå og derfor laver /&¤&. 
Tror der mangler noget encoding :) 

Det virker fint hvis man markere navnet for at lave en filtrering på det. Så fremstår navnet med æøå.

**Comment by kenger-dk** [comment]
fixed.. missed a html parsing
