### ISSUE TITLE
The connection was not closed exception

### ISSUE THREAD

**Issue by Mihgo** [kenger-dk/DAW#76]
![be6b9f66](https://user-images.githubusercontent.com/34692014/51841213-60ad5f80-230e-11e9-8377-757085edac3c.PNG)

Kommer frem ved manuel indtastning.

**Comment by Mihgo** [comment]
Den kom også da jeg ville slette flere rows

**Comment by kenger-dk** [comment]
issue have been reproduced, critical issue, working on fix

**Comment by kenger-dk** [comment]
fixed, and ready for testing tomorrow, if needed we will provide a fix for 2.6 to, please request if needed.
