### ISSUE TITLE
compile error (v. 2.8.45.385)

### ISSUE THREAD

**Issue by SIT-kenger** [kenger-dk/DAW#91]
when listing a table, we get a compile error:

CS0012: The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.  DAWGrid.ascx    Line: 250 
Line 248:                        <%}%>
Line 249:
Line 250:                        <% if (GetCustomWebHooks.Count() != 0) { %>
Line 251:                        sep2: "---------",
Line 252:                        <%}%>

**Comment by kenger-dk** [comment]
cant reproduce, please test again, have redeployed

**Comment by SIT-kenger** [comment]
I had to add this på web.config to get it working??
	<add assembly="System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />

**Comment by kenger-dk** [comment]
added to web.config
